### ISSUE TITLE
IEntityRemoveSystem没有正确监听到entity删除，反而在entity.remove(组件)的时候会被调用

### ISSUE THREAD

**Issue by wanghuatao** [shangdibaozi/ECS#12]
重现代码如下:
import { ecs } from "./ECS";
@ecs.register('Hello')
export class HelloComponent extends ecs.Comp {
    info: string;
    // 组件被回收前会调用这个方法。
    reset() {
        this.info = '';
    }
}

export class TestHelloSystem extends ecs.ComblockSystem implements  ecs.IEntityRemoveSystem {
    entityRemove(entities: ecs.Entity[]): void {
        console.log('TestSystem entityRemove');
    }
    filter(): ecs.IMatcher {
        return ecs.allOf(HelloComponent);
    }
    update(entities: ecs.Entity[]): void {
    }

export default class RoomSystem extends ecs.RootSystem {
    constructor() {
        super();
        this.add(new TestHelloSystem());
    }
}

//调用如下:

            let entity = ecs.createEntity();
            entity.add(HelloComponent);
            setInterval(() => {
                //会触发entityRemove
               entity.remove(HelloComponent);
            }, 4000);

**Comment by shangdibaozi** [comment]
“反而在entity.remove(组件)的时候会被调用”是什么意思？

**Comment by wanghuatao** [comment]
let entity = ecs.createEntity();
        entity.add(HelloComponent);
        setInterval(() => {
            // 这里会触发entityRemove，正常逻辑来说应该只会有组件移除的事件才对
           entity.remove(HelloComponent);
        }, 4000);

**Comment by shangdibaozi** [comment]
因为你的TestHelloSystem只是监听了包含HelloComponent的实体集合。

**Comment by shangdibaozi** [comment]
更准确的说，TestHelloSystem监听包含HelloComponent的实体的集合，如果一个实体没有了HelloComponent，那么这个实体就不属于这个集合，从而导致触发entityRemove方法。

**Comment by wanghuatao** [comment]
let entity = ecs.createEntity();
entity.add(HelloComponent);
entity.add(**WorldComponent**);
setInterval(() => {
// 这里会触发entityRemove，正常逻辑来说应该只会有组件移除的事件才对
entity.remove(HelloComponent);
}, 4000);

这样子也会

**Comment by shangdibaozi** [comment]
TestHelloSystem中ecs.allOf(HelloComponent)表示只关心有HelloComponent组件的实体，如果实体删除了HelloComponent，那么对于TestHelloSystem来说，这个实体就不满足TestHelloSystem对实体的筛选条件，所以会触发entityRemove。
